name: filebase_chat_app
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  zego_uikit_prebuilt_call: ^3.18.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_database: ^10.3.8
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  loading_animation_widget: ^1.2.0+4
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  timeago: ^3.6.0
  image_picker: ^1.0.5
  provider: ^6.1.1
  firebase_messaging: ^14.7.9
  flutter_local_notifications: ^16.3.0
  http: ^1.1.0
  url_launcher: ^6.2.3
  # Splash
  flutter_native_splash: ^2.3.7
  # easy_localization  change language
  easy_localization: ^3.0.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/logo.png
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: assets/images/logo_foreground.png

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#2D3250"
  image: 'assets/images/splash_logo.png'


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

